/* 日常：离线优先。数据保存在 localStorage，可通过设置页导出备份。 */
const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const STORE = 'daily-practice-v1';
// 内阁府公布的 2026 年国民の祝日・休日（含振替休日与国民の休日）。
const JAPAN_HOLIDAYS_2026 = ['2026-01-01','2026-01-12','2026-02-11','2026-02-23','2026-03-20','2026-04-29','2026-05-03','2026-05-04','2026-05-05','2026-05-06','2026-07-20','2026-08-11','2026-09-21','2026-09-22','2026-09-23','2026-10-12','2026-11-03','2026-11-23'];
const today = new Date(); today.setHours(0,0,0,0);
let selectedDate = new Date(today), calendarDate = new Date(today), heatmapMonth = new Date(today.getFullYear(),today.getMonth(),1), range = 'day', reminderTab = 'upcoming';
const seed = {tasks:[
  {id:'words',name:'日语：每天背10个单词',frequency:'daily',unit:'个',target:10,description:'记录当天背诵的单词'},
  {id:'phrase',name:'日语：每天背一句商务短句',frequency:'daily',unit:'句',target:1,description:'记录当天背诵的商务短句'},
  {id:'run',name:'运动：每月跑步30公里',frequency:'daily',unit:'公里',target:1,monthlyTarget:30,description:'每月累计跑步 30 公里'},
  {id:'reading',name:'读书：每天30分钟',frequency:'daily',unit:'分钟',target:30,description:'记录当天读书时长'},
  {id:'early',name:'早起：每天6点起床',frequency:'daily',unit:'次',target:1,description:'每天 6 点起床'},
  {id:'meditate',name:'静心：每天拒绝坏习惯',frequency:'daily',unit:'次',target:1,description:'记录当天拒绝的坏习惯'}
], logs:[], events:[],reminders:[{id:'credit-card',name:'信用卡还款',days:[10]},{id:'monthly-report',name:'提交月报',days:[30]}],reminderDismissals:[],holidays:[],companyDaysOff:[]};
let cloud={client:null,user:null,saveTimer:null};
let data = load();
function normalizeData(value){let d=value&&typeof value==='object'?value:structuredClone(seed);d.tasks??=[];d.logs??=[];d.events??=[];d.reminders??=[];d.reminderDismissals??=[];d.holidays=[...new Set([...(d.holidays||[]),...JAPAN_HOLIDAYS_2026])].sort();d.companyDaysOff??=[];for(let id of ['attendance','bills','report']){let old=d.tasks.find(t=>t.id===id);if(old&&!d.reminders.some(r=>r.id===id))d.reminders.push({id,name:old.name,...(old.id==='report'?{endOfMonth:true}:{days:old.days||[]})});d.tasks=d.tasks.filter(t=>t.id!==id)}let report=d.reminders.find(r=>r.id==='report');if(report){report.endOfMonth=true;delete report.days}for(let t of seed.tasks.filter(t=>!['attendance','bills','report'].includes(t.id))){if(!d.tasks.some(x=>x.id===t.id))d.tasks.push(structuredClone(t))}let run=d.tasks.find(t=>t.id==='run');if(run&&run.target===40){run.target=3;run.monthlyTarget=40}return d}
function load(){try{return normalizeData(JSON.parse(localStorage.getItem(STORE)))}catch{return normalizeData(null)}}
function save(){localStorage.setItem(STORE,JSON.stringify(data));render();queueCloudSave()}
function queueCloudSave(){if(!cloud.client||!cloud.user)return;clearTimeout(cloud.saveTimer);cloud.saveTimer=setTimeout(saveCloud,500)}
async function saveCloud(){if(!cloud.client||!cloud.user)return;let {error}=await cloud.client.from('user_state').upsert({user_id:cloud.user.id,data,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)showAuthMessage(`同步失败：${error.message}`,true)}
function key(d=selectedDate){return dateKey(d)}
function dateKey(d){return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
function parseDate(s){const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)}
function lastDay(d){return new Date(d.getFullYear(),d.getMonth()+1,0).getDate()}
function fmt(d,{short=false}={}){return d.toLocaleDateString('zh-CN',{month:short?'numeric':'long',day:'numeric',weekday:short?undefined:'long'})}
function sameDate(a,b){return dateKey(a)===dateKey(b)}
function taskDue(t,d){return t.frequency==='daily'||(t.frequency==='monthly'&&(t.days||[]).includes(d.getDate())||t.id==='report'&&d.getDate()===lastDay(d))}
function logsFor(d=selectedDate){return data.logs.filter(l=>l.date===key(d))}
function logFor(task,d=selectedDate){return data.logs.find(l=>l.taskId===task.id&&l.date===key(d))}
function monthLogs(d=selectedDate){return data.logs.filter(l=>{const x=parseDate(l.date);return x.getFullYear()===d.getFullYear()&&x.getMonth()===d.getMonth()})}
function completed(t,d=selectedDate){const l=logFor(t,d);return !!l&&l.done}
function runTotal(d=selectedDate){return monthLogs(d).filter(l=>l.taskId==='run'&&l.done).reduce((n,l)=>n+(Number(l.amount)||0),0)}
function dueTasks(d=selectedDate){return data.tasks.filter(t=>taskDue(t,d))}
function displayLunarDate(value=''){return String(value).replace(/[农陰阴]历/g,'').replace(/[0-9〇零一二三四五六七八九十]{4}年/g,'').replace(/\s/g,'')}
function chineseDayToNumber(value){let s=value.replace(/日/g,''),n={零:0,一:1,二:2,三:3,四:4,五:5,六:6,七:7,八:8,九:9};if(/^\d+$/.test(s))return Number(s);if(s==='十'||s==='初十')return 10;if(s.startsWith('初'))return n[s[1]]||0;if(s.startsWith('十'))return 10+(n[s[1]]||0);if(s.startsWith('廿'))return 20+(n[s[1]]||0);if(s.startsWith('卅'))return 30+(n[s[1]]||0);return n[s]||0}
function normalizeLunarDate(value=''){let s=displayLunarDate(value),match=s.match(/([正一二三四五六七八九十冬腊\d]+)[月-]([初十廿卅一二三四五六七八九零\d]+)日?/);if(!match)return s;let months={正:1,一:1,二:2,三:3,四:4,五:5,六:6,七:7,八:8,九:9,十:10,冬:11,腊:12},m=/^\d+$/.test(match[1])?Number(match[1]):months[match[1]],d=chineseDayToNumber(match[2]);return m&&d?`${m}-${d}`:s}
function lunarString(d){try{return normalizeLunarDate(new Intl.DateTimeFormat('zh-CN-u-ca-chinese',{month:'numeric',day:'numeric'}).format(d))}catch{return ''}}
function eventOn(e,d){if(e.repeat==='once')return e.date===dateKey(d);if(e.repeat==='solar'){let x=parseDate(e.date);return x.getMonth()===d.getMonth()&&x.getDate()===d.getDate()}if(e.repeat==='lunar')return lunarString(d)===normalizeLunarDate(e.lunarDate);return false}
function upcoming(){let all=[];for(let i=0;i<366;i++){let d=new Date(today);d.setDate(d.getDate()+i);data.events.filter(e=>eventOn(e,d)).forEach(e=>all.push({e,d}))}return all.slice(0,5)}
function render(){renderToday();renderOverview();renderSettings();renderMiniCalendar();$('.date-display').textContent=today.toLocaleDateString('zh-CN',{year:'numeric',month:'short',day:'numeric'});}
function renderToday(){let done=logsFor(today).filter(l=>l.done).length;$('#done-count').textContent=`本日 ${done}/${data.tasks.length} 已完成`;renderMonthHeatmap();renderReminders();}
function monthlyTaskTotal(t,d=heatmapMonth){let logs=monthLogs(d).filter(l=>l.taskId===t.id&&l.done);if(t.id==='run')return logs.reduce((n,l)=>n+(Number(l.amount)||0),0).toFixed(1).replace(/\.0$/,'');let amounts=logs.filter(l=>l.amount!=='').reduce((n,l)=>n+(Number(l.amount)||0),0);return amounts||logs.length}
function renderMonthHeatmap(){let d=heatmapMonth,days=new Date(d.getFullYear(),d.getMonth()+1,0).getDate(),html='<div class="hm-label">任务 / 日期</div><div class="hm-total-head">本月</div>';for(let i=1;i<=days;i++)html+=`<div class="hm-day">${String(i).padStart(2,'0')}</div>`;data.tasks.forEach((t,ti)=>{let total=monthlyTaskTotal(t,d),suffix=t.unit||'';html+=`<div class="hm-label hm-tone-${ti%6}">${esc(t.name)}</div><div class="hm-total hm-tone-${ti%6}">${total}${suffix}</div>`;for(let i=1;i<=days;i++){let x=new Date(d.getFullYear(),d.getMonth(),i),l=logFor(t,x),amount=Number(l?.amount),ratio=l?.done&&Number.isFinite(amount)?amount/Math.max(1,Number(t.target)||1):0,level=!l?.done?0:l.amount===''?1:ratio>=1.5?3:ratio>=1?2:1,value=l?.amount!==''&&l?.amount!==undefined?`<span>${esc(String(l.amount).slice(0,2))}</span>`:'';html+=`<button class="hm-cell l${level}" data-hm-date="${dateKey(x)}" data-hm-task="${t.id}" title="${t.name} · ${i}日${l?.done?'：已记录':'：未记录'}">${value}</button>`}});$('#heatmap-title').textContent=`${d.getFullYear()}年${d.getMonth()+1}月`;$('#month-heatmap').style.setProperty('--days',days);$('#month-heatmap').innerHTML=html;$$('[data-hm-date]').forEach(b=>b.onclick=()=>{selectedDate=parseDate(b.dataset.hmDate);openEntry(b.dataset.hmTask)})}
function nextReminderDates(){let out=[];for(let r of data.reminders){for(let i=0;i<60;i++){let d=new Date(today);d.setDate(d.getDate()+i);if(r.endOfMonth?d.getDate()===lastDay(d):r.days.includes(d.getDate())){out.push({id:r.id,name:r.name,date:d,kind:'recurring'});break}}}for(let e of data.events){for(let i=0;i<60;i++){let d=new Date(today);d.setDate(d.getDate()+i);if(eventOn(e,d)){out.push({id:e.id,name:e.name,date:d,kind:'event',lunarDate:e.repeat==='lunar'?displayLunarDate(e.lunarDate):''});break}}}return out.sort((a,b)=>a.date-b.date)}
function reminderKey(r){return `${r.id}@${dateKey(r.date)}`}
function renderReminders(){let all=nextReminderDates(),dismissed=new Set(data.reminderDismissals),rows=reminderTab==='upcoming'?all.filter(r=>!dismissed.has(reminderKey(r))):all.filter(r=>dismissed.has(reminderKey(r)));$('#reminder-list').innerHTML=rows.length?rows.map(r=>{let detail=r.lunarDate?`农历 ${r.lunarDate}`:r.kind==='recurring'?'定期':'重要事项';return `<article class="reminder"><span class="reminder-date">${r.date.getMonth()+1}/${r.date.getDate()}</span><strong>${esc(r.name)}</strong><span class="reminder-kind">${esc(detail)}</span><button class="reminder-action" data-reminder-action="${reminderKey(r)}">${reminderTab==='upcoming'?'完成':'恢复'}</button></article>`}).join(''):`<p class="muted reminder-empty">${reminderTab==='upcoming'?'近期没有待提醒事项。':'没有已完成的提醒。'}</p>`;$$('[data-reminder-action]').forEach(b=>b.onclick=()=>{let k=b.dataset.reminderAction;if(reminderTab==='upcoming')data.reminderDismissals.push(k);else data.reminderDismissals=data.reminderDismissals.filter(x=>x!==k);save()})}
function toggleTask(id){let t=data.tasks.find(x=>x.id===id),l=logFor(t);if(l){l.done=!l.done;if(!l.done){l.amount='';l.note=''}}else data.logs.push({id:crypto.randomUUID(),taskId:id,date:key(),done:true,amount:t.id==='words'?10:t.id==='phrase'?1:'',note:''});save()}
function openEntry(id){let t=data.tasks.find(x=>x.id===id),l=logFor(t)||{};$('#entry-task-id').value=id;$('#dialog-title').textContent=`记录：${t.name}`;$('#dialog-kicker').textContent=fmt(selectedDate);$('#entry-amount').value=l.amount??(t.id==='run'?'':t.target??'');$('#entry-amount').placeholder=t.unit?`例如 ${t.target||1} ${t.unit}`:'可选';$('#amount-field').firstChild.textContent=t.unit?`完成数量（${t.unit}，可选，最多两位）`:'完成数量（可选，最多两位）';$('#entry-note').value=l.note||'';$('#remove-entry').hidden=!l.done;$('#entry-dialog').showModal()}
function renderOverview(){let m=monthLogs(), todayDone=logsFor().filter(x=>x.done).length, days=new Set(m.filter(x=>x.done).map(x=>x.date)).size, run=runTotal(),runTask=data.tasks.find(t=>t.id==='run'),runGoal=Number(runTask?.monthlyTarget)||0,runUnit=runTask?.unit||'公里';$('#summary-cards').innerHTML=`<article class="summary"><span class="muted">今日完成</span><b>${todayDone}<small> 项</small></b></article><article class="summary"><span class="muted">本月打卡天数</span><b>${days}<small> 天</small></b></article><article class="summary"><span class="muted">本月跑量</span><b>${run.toFixed(run%1?1:0)}<small>${runGoal?` / ${runGoal} ${runUnit}`:''}</small></b></article>`;
 let count=range==='day'?7:range==='week'?8:6, labels=[], values=[];for(let i=count-1;i>=0;i--){let d=new Date(today);if(range==='day')d.setDate(d.getDate()-i);else if(range==='week')d.setDate(d.getDate()-i*7);else d.setMonth(d.getMonth()-i);let v;if(range==='day')v=logsFor(d).filter(l=>l.done).length;else {let start=new Date(d), end=new Date(d);if(range==='week'){start.setDate(start.getDate()-6)}else {start.setDate(1);end.setMonth(end.getMonth()+1,0)}v=data.logs.filter(l=>l.done&&parseDate(l.date)>=start&&parseDate(l.date)<=end).length}labels.push(range==='month'?`${d.getMonth()+1}月`:range==='week'?`第${count-i}周`:`${d.getMonth()+1}/${d.getDate()}`);values.push(v)}let max=Math.max(1,...values);$('#chart-caption').textContent=range==='day'?'近 7 天':range==='week'?'近 8 周':'近 6 个月';$('#bar-chart').innerHTML=values.map((v,i)=>`<div class="bar ${sameDate((()=>{let x=new Date(today);return x})(),today)&&i===values.length-1?'today-bar':''}" style="height:${Math.max(5,v/max*100)}%" title="${labels[i]}：${v} 项"><span>${labels[i]}</span></div>`).join('');
 let recent=[...data.logs].filter(x=>x.done).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8);$('#recent-logs').innerHTML=recent.length?recent.map(l=>{let t=data.tasks.find(t=>t.id===l.taskId);return `<div class="log-row"><span class="muted">${l.date.slice(5)}</span><strong>${esc(t?.name||'已删除任务')}</strong><span>${esc([l.amount&&t?.unit?`${l.amount}${t.unit}`:'',l.note].filter(Boolean).join(' · ')||'完成')}</span></div>`}).join(''):'<p class="empty-state">还没有记录，从今天开始吧。</p>'}
function renderMiniCalendar(){let y=calendarDate.getFullYear(),m=calendarDate.getMonth(),first=new Date(y,m,1).getDay(),n=new Date(y,m+1,0).getDate(),html=Array.from({length:first},()=>'<span class="mini-day empty"></span>').join('');$('#mini-calendar-title').textContent=`${y}年${m+1}月`;for(let i=1;i<=n;i++){let d=new Date(y,m,i),k=dateKey(d),weekday=d.getDay(),kind=data.companyDaysOff.includes(k)?' company-off':data.holidays.includes(k)?' legal-holiday':weekday===0?' sunday':weekday===6?' saturday':'';html+=`<span class="mini-day ${kind}${sameDate(d,today)?' today':''}">${i}</span>`}$('#mini-calendar-grid').innerHTML=html}
function renderSettings(){let taskHTML=data.tasks.map(t=>`<div class="setting-row"><div class="setting-title"><strong>${esc(t.name)}</strong><small>${t.frequency==='daily'?'每天':`每月 ${t.days?.join('、')||'月末'} 日`} ${t.target?`· 目标 ${t.target}${t.unit||''}`:''}</small></div><button class="record-btn" data-edit-task="${t.id}">编辑</button></div>`).join('');$('#task-settings').innerHTML=taskHTML;let eventHTML=data.events.map(e=>`<div class="setting-row"><div class="setting-title"><strong>${esc(e.name)}</strong><small>${e.repeat==='once'?e.date:e.repeat==='solar'?`每年阳历 ${e.date.slice(5)}`:`每年农历 ${e.lunarDate}`}</small></div><button class="record-btn" data-edit-event="${e.id}">编辑</button></div>`).join('')||'<p class="empty-state">暂无重要提醒。</p>';$('#event-settings').innerHTML=eventHTML;$('#holiday-dates').value=data.holidays.join(', ');$('#company-off-dates').value=data.companyDaysOff.join(', ');$$('[data-edit-task]').forEach(b=>b.onclick=()=>openTaskEditor(b.dataset.editTask));$$('[data-edit-event]').forEach(b=>b.onclick=()=>openItem('event',b.dataset.editEvent));}
function openItem(type,id=''){let o=id?(type==='task'?data.tasks:data.events).find(x=>x.id===id):{},isEvent=type==='event';$('#item-type').value=type;$('#item-id').value=id;$('#item-title').textContent=id?'编辑项目':isEvent?'添加重要提醒':'添加任务';$('#item-kicker').textContent=isEvent?'REMINDER':'TASK';$('#item-name').value=o.name||'';$('#item-frequency').value=o.frequency||'daily';$('#item-days').value=(o.days||[]).join(',');$('#item-unit').value=o.unit||'';$('#item-target').value=o.target||'';$('#event-date').value=o.date||dateKey(today);$('#event-repeat').value=o.repeat||'once';$('#lunar-date').value=o.lunarDate||'';$('#item-frequency-wrap').hidden=isEvent;$('#item-days-wrap').hidden=isEvent;$('#item-unit-wrap').hidden=isEvent;$('#item-target-wrap').hidden=isEvent;$('#event-date-wrap').hidden=!isEvent;$('#event-repeat-wrap').hidden=!isEvent;$('#lunar-date-wrap').hidden=!isEvent||$('#event-repeat').value!=='lunar';$('.delete-current').hidden=!id;$('#item-dialog').showModal()}
function esc(v=''){let d=document.createElement('div');d.textContent=v;return d.innerHTML}
function supabaseConfig(){let c=window.SUPABASE_CONFIG||{};return {url:c.url,key:c.publishableKey||c.anonKey}}
function showAuthMessage(message='',isError=false){let el=$('#auth-message');if(!el)return;el.textContent=message;el.classList.toggle('error',isError)}
function authRedirectUrl(){return /^https?:$/.test(location.protocol)?location.href.split('#')[0]:undefined}
function updateAuthUI(){let signed=!!cloud.user;$('#auth-button').textContent=signed?`${cloud.user.email} · 已同步`:'登录同步';$('#sign-out').hidden=!signed;if(signed)showAuthMessage('已登录；此后的修改会自动同步。')}
async function hydrateFromCloud(){if(!cloud.client||!cloud.user)return;showAuthMessage('正在读取云端数据…');let {data:row,error}=await cloud.client.from('user_state').select('data').eq('user_id',cloud.user.id).maybeSingle();if(error){showAuthMessage(`无法读取云端数据：${error.message}`,true);return}if(row?.data&&Object.keys(row.data).length){data=normalizeData(row.data);localStorage.setItem(STORE,JSON.stringify(data));render();showAuthMessage('已读取云端数据。')}else{showAuthMessage('云端暂无数据，正在上传当前本地数据…');await saveCloud();showAuthMessage('已创建云端备份。')}}
async function initSupabase(){let {url,key}=supabaseConfig();if(!url||!key||!window.supabase){updateAuthUI();return}try{cloud.client=window.supabase.createClient(url,key);let {data:sessionData,error}=await cloud.client.auth.getSession();if(error)throw error;cloud.user=sessionData.session?.user||null;updateAuthUI();if(cloud.user)await hydrateFromCloud();cloud.client.auth.onAuthStateChange((event,session)=>{cloud.user=session?.user||null;updateAuthUI();if(event==='SIGNED_IN'&&cloud.user)hydrateFromCloud()})}catch(error){showAuthMessage(`Supabase 配置无法使用：${error.message}`,true)}}
function authValues(){return {email:$('#auth-email').value.trim(),password:$('#auth-password').value}}
async function signIn(){if(!cloud.client){showAuthMessage('请先在 supabase-config.js 填写 Project URL 与 publishable key。',true);return}let {email,password}=authValues();if(!email||!password)return;showAuthMessage('正在登录…');let {error}=await cloud.client.auth.signInWithPassword({email,password});if(error)showAuthMessage(`登录失败：${error.message}`,true)}
async function signUp(){if(!cloud.client){showAuthMessage('请先在 supabase-config.js 填写 Project URL 与 publishable key。',true);return}let {email,password}=authValues(),redirectTo=authRedirectUrl();if(!email||!password)return;showAuthMessage('正在注册…');let {data:result,error}=await cloud.client.auth.signUp({email,password,options:redirectTo?{emailRedirectTo:redirectTo}:undefined});if(error){showAuthMessage(`注册失败：${error.message}`,true);return}showAuthMessage(result.session?'注册并登录成功。':'注册成功，请到邮箱完成验证后再登录。')}
async function resendConfirmation(){if(!cloud.client){showAuthMessage('请先在 supabase-config.js 填写 Project URL 与 publishable key。',true);return}let {email}=authValues(),redirectTo=authRedirectUrl();if(!email){showAuthMessage('请先填写邮箱地址。',true);return}showAuthMessage('正在发送确认邮件…');let {error}=await cloud.client.auth.resend({type:'signup',email,options:redirectTo?{emailRedirectTo:redirectTo}:undefined});showAuthMessage(error?`发送失败：${error.message}`:'已发送新的确认邮件，请只打开最新的一封。',!!error)}
// events
function showView(id){$$('.view').forEach(x=>x.classList.toggle('active',x.id===id))}
$$('.range').forEach(b=>b.onclick=()=>{range=b.dataset.range;$$('.range').forEach(x=>x.classList.toggle('active',x===b));renderOverview()});
$('#entry-form').addEventListener('submit',e=>{e.preventDefault();let id=$('#entry-task-id').value,t=data.tasks.find(t=>t.id===id),amount=$('#entry-amount').value;if(amount!==''&&(!Number.isInteger(Number(amount))||Number(amount)<0||Number(amount)>99)){alert('数字请填写 0 到 99 的整数。');return}let l=logFor(t)||{id:crypto.randomUUID(),taskId:id,date:key()};l.done=true;l.amount=amount;l.note=$('#entry-note').value.trim();if(!logFor(t))data.logs.push(l);$('#entry-dialog').close();save()});
$$('.close-entry').forEach(b=>b.onclick=()=>$('#entry-dialog').close());
$('#remove-entry').onclick=()=>{let t=data.tasks.find(t=>t.id===$('#entry-task-id').value),l=logFor(t);if(l){data.logs=data.logs.filter(x=>x.id!==l.id);$('#entry-dialog').close();save()}};
$('#add-task').onclick=()=>openTaskEditor();$('#add-event').onclick=()=>openItem('event');$('#event-repeat').onchange=()=>$('#lunar-date-wrap').hidden=$('#event-repeat').value!=='lunar';
$('#heatmap-prev').onclick=()=>{heatmapMonth.setMonth(heatmapMonth.getMonth()-1);renderToday()};$('#heatmap-next').onclick=()=>{heatmapMonth.setMonth(heatmapMonth.getMonth()+1);renderToday()};$$('.reminder-tab').forEach(b=>b.onclick=()=>{reminderTab=b.dataset.reminderTab;$$('.reminder-tab').forEach(x=>x.classList.toggle('active',x===b));renderReminders()});
$('#open-settings').onclick=()=>showView('settings');$('#back-to-today').onclick=()=>showView('today');$('#mini-prev').onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()-1);renderMiniCalendar()};$('#mini-next').onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()+1);renderMiniCalendar()};$('#save-calendar-days').onclick=()=>{let parse=s=>[...new Set(s.split(',').map(x=>x.trim()).filter(x=>/^\d{4}-\d{2}-\d{2}$/.test(x)))];data.holidays=[...new Set([...JAPAN_HOLIDAYS_2026,...parse($('#holiday-dates').value)])].sort();data.companyDaysOff=parse($('#company-off-dates').value);save()};
function openTaskEditor(id=''){let task=id?data.tasks.find(t=>t.id===id):null;$('#editing-task-id').value=id;$('#task-add-title').textContent=task?'编辑打卡项目':'追加打卡项目';$('#task-add-submit').textContent=task?'保存':'追加';$('#new-task-name').value=task?.name||'';$('#new-task-target').value=task?.target||1;$('#new-task-unit').value=task?.unit||'';$('#new-task-description').value=task?.description||'';$('#task-add-dialog').showModal()}
$('#add-checkin-task').onclick=()=>openTaskEditor();$$('.close-task-add').forEach(b=>b.onclick=()=>$('#task-add-dialog').close());$('#task-add-form').addEventListener('submit',e=>{e.preventDefault();let name=$('#new-task-name').value.trim(),target=Number($('#new-task-target').value),id=$('#editing-task-id').value;if(!name||!Number.isInteger(target)||target<1||target>99)return;let task=id?data.tasks.find(t=>t.id===id):null;if(task){Object.assign(task,{name,unit:$('#new-task-unit').value.trim(),target,description:$('#new-task-description').value.trim()})}else data.tasks.push({id:crypto.randomUUID(),name,frequency:'daily',unit:$('#new-task-unit').value.trim(),target,description:$('#new-task-description').value.trim()});$('#task-add-dialog').close();save()});
function setReminderAddType(type){let dialog=$('#reminder-add-dialog');dialog.classList.remove('mode-once','mode-monthly','mode-yearly');dialog.classList.add(`mode-${type}`);$$('.reminder-type-option').forEach(b=>{let active=b.dataset.newReminderType===type;b.classList.toggle('active',active);b.setAttribute('aria-checked',active)})}
function setReminderCalendarType(type){let dialog=$('#reminder-add-dialog');dialog.classList.toggle('calendar-solar',type==='solar');dialog.classList.toggle('calendar-lunar',type==='lunar');$$('.calendar-type-option').forEach(b=>b.classList.toggle('active',b.dataset.calendarType===type))}
$('#add-reminder').onclick=()=>{setReminderAddType('once');setReminderCalendarType('solar');$('#reminder-add-dialog').showModal()};$$('.close-reminder-add').forEach(b=>b.onclick=()=>$('#reminder-add-dialog').close());$$('.reminder-type-option').forEach(b=>b.onclick=()=>setReminderAddType(b.dataset.newReminderType));$$('.calendar-type-option').forEach(b=>b.onclick=()=>setReminderCalendarType(b.dataset.calendarType));$('#reminder-add-form').addEventListener('submit',e=>{e.preventDefault();let name=$('#new-reminder-name').value.trim(),type=$('.reminder-type-option.active').dataset.newReminderType;if(!name)return;if(type==='once'){let date=$('#new-reminder-date').value;if(!date)return;data.events.push({id:crypto.randomUUID(),name,date,repeat:'once'})}else if(type==='monthly'){let days=$('#new-reminder-days').value.split(',').map(Number).filter(x=>x>0&&x<32);if(!days.length)return;data.reminders.push({id:crypto.randomUUID(),name,days})}else{let calendarType=$('.calendar-type-option.active').dataset.calendarType;if(calendarType==='solar'){let date=$('#new-reminder-solar-date').value;if(!date)return;data.events.push({id:crypto.randomUUID(),name,date,repeat:'solar'})}else{let lunarDate=$('#new-reminder-lunar-date').value.trim();if(!lunarDate)return;data.events.push({id:crypto.randomUUID(),name,repeat:'lunar',lunarDate})}}$('#reminder-add-dialog').close();e.target.reset();setReminderAddType('once');setReminderCalendarType('solar');save()});
$('#item-form').addEventListener('submit',e=>{e.preventDefault();let type=$('#item-type').value,id=$('#item-id').value,list=type==='task'?data.tasks:data.events,o=id?list.find(x=>x.id===id):{id:crypto.randomUUID()};o.name=$('#item-name').value.trim();if(type==='task'){o.frequency=$('#item-frequency').value;o.days=$('#item-days').value.split(',').map(Number).filter(x=>x>0&&x<32);o.unit=$('#item-unit').value.trim();o.target=Number($('#item-target').value)||0;o.description=o.frequency==='daily'?'每日坚持':'每月固定日期'}else{o.date=$('#event-date').value;o.repeat=$('#event-repeat').value;o.lunarDate=$('#lunar-date').value.trim();if(o.repeat==='lunar'&&!o.lunarDate){alert('请填写农历日期，例如：八月十五');return}}if(!o.name){return}if(!id)list.push(o);$('#item-dialog').close();save()});
$('.delete-current').onclick=()=>{let type=$('#item-type').value,id=$('#item-id').value;if(!confirm('确定删除这个项目吗？已有记录会保留。'))return;if(type==='task')data.tasks=data.tasks.filter(x=>x.id!==id);else data.events=data.events.filter(x=>x.id!==id);$('#item-dialog').close();save()};
$('#export-data').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=`日常备份-${dateKey(today)}.json`;a.click();URL.revokeObjectURL(a.href)};$('#import-data').onclick=()=>$('#import-file').click();$('#import-file').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!Array.isArray(x.tasks)||!Array.isArray(x.logs))throw Error();if(confirm('导入将覆盖当前数据，确定继续吗？')){data=normalizeData(x);save()}}catch{alert('这不是有效的日常备份文件。')}};r.readAsText(f)};$('#reset-data').onclick=()=>{if(confirm('这会删除浏览器内的所有任务和记录，且无法撤销。确定吗？')){data=normalizeData(null);save()}};
$('#auth-button').onclick=()=>{let {url,key}=supabaseConfig();if(!url||!key)showAuthMessage('先完成 Supabase 配置：填写 Project URL 与 publishable key。',true);else showAuthMessage(cloud.user?'已登录；本页的更改会自动同步。':'');$('#auth-dialog').showModal()};$$('.close-auth').forEach(b=>b.onclick=()=>$('#auth-dialog').close());$('#auth-form').addEventListener('submit',e=>{e.preventDefault();signIn()});$('#sign-up').onclick=signUp;$('#resend-confirmation').onclick=resendConfirmation;$('#sign-out').onclick=async()=>{if(cloud.client)await cloud.client.auth.signOut();cloud.user=null;updateAuthUI();showAuthMessage('已退出登录；本地数据仍保留在此浏览器。')};
render();
initSupabase();
